defaults: &defaults
  docker:
    - image: circleci/node:11-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - package-v1-{{ checksum "package.json" }}
      - run:
          name: Dependencies
          command: npm install
      - save_cache:
          key: package-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
            - deploy
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Add GitHub Host Key
          command: |
            mkdir ~/.ssh
            cat << EOF > ~/.ssh/known_hosts
            |1|M8mwfAoxBaYJcLo5YfaNfAOb0/0=|6+q9cMMStegPYI2LqDrWQC0Lw6Y= ssh-rsa \
            AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
            EOF
      - run:
          name: Deploy to gh-pages
          command: cd dist && ../deploy

workflows:
  version: 2
  test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
